# Jekyll configuration for GitHub Pages
title: PulsePal Documentation
description: MRI Sequence Programming Assistant Documentation

# Include files
include:
  - sequences/

# Keep files as-is
keep_files:
  - sequences/sequence_catalog.json

# Plugins
plugins:
  - jekyll-relative-links

# Process all files
relative_links:
  enabled: true
  collections: false
